name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write   # Required for OIDC Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Build sdist & wheel (uvx build)
        run: uvx build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
