name: Publish to TestPyPI

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build sdist & wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          print-hash: true